import { AllList } from './allList.type';

export const allList: AllList = {
  boss: [
    {
      category: 'boss',
      name: 'Astol',
      loc: 'Aulada Ancient Tower',
      ele: 'wind',
      stats: {
        ez: {
          lv: 40,
          exp: 76,
          hp: 8204,
        },
        normal: {
          lv: 50,
          exp: 760,
          hp: 82040,
          npror: 6,
          ppror: 25,
          mpror: 25,
          pres: 1,
          mres: 1,
          def: 50,
          mdef: 150,
          flee: 112,
          guard: 0,
          evade: 15,
          cres: 0,
        },
        hard: {
          lv: 60,
          exp: 1520,
          hp: 164080,
        },
        nm: {
          lv: 70,
          exp: 3800,
          hp: 410200,
        },
        ulti: {
          lv: 90,
          exp: 7600,
          hp: 820400,
        },
      },
    },
    {
      category: 'boss',
      name: 'Ancient Empress Mezzaluna',
      loc: 'Ancient Empress Tomb: Deepest Part',
      ele: 'light',
      stats: {
        ez: {
          lv: 54,
          exp: 312,
          hp: 130000,
        },
        normal: {
          lv: 64,
          exp: 3120,
          hp: 130000,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 52,
          mres: 52,
          def: 32,
          mdef: 392,
          flee: 48,
          guard: 10,
          evade: 1,
          cres: 0,
        },
        hard: {
          lv: 74,
          exp: 6240,
          hp: 260000,
        },
        nm: {
          lv: 84,
          exp: 15600,
          hp: 650000,
        },
        ulti: {
          lv: 104,
          exp: 31200,
          hp: 1300000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Arachnidemon',
      loc: 'Arche Valley: Depths',
      ele: 'dark',
      stats: {
        ez: {
          lv: 186,
          exp: 1160,
          hp: 239400,
        },
        normal: {
          lv: 196,
          exp: 11600,
          hp: 2394000,
          npror: 10,
          ppror: 20,
          mpror: 20,
          pres: 7,
          mres: 7,
          def: 512,
          mdef: 392,
          flee: 351,
          guard: undefined,
          evade: undefined,
          cres: 0,
        },
        hard: {
          lv: 206,
          exp: 23200,
          hp: 4788000,
        },
        nm: {
          lv: 216,
          exp: 58000,
          hp: 11970000,
        },
        ulti: {
          lv: 236,
          exp: 116000,
          hp: 23940000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Aranea',
      loc: 'Garden of Sublimation: Central Part',
      ele: 'fire',
      stats: {
        ez: {
          lv: 90,
          exp: 440,
          hp: 38000,
        },
        normal: {
          lv: 100,
          exp: 4400,
          hp: 380000,
          npror: 10,
          ppror: 20,
          mpror: 15,
          pres: 4,
          mres: 4,
          def: {
            ph1: 130,
            ph2: 120,
          },
          mdef: {
            ph1: 110,
            ph2: 100,
          },
          flee: {
            ph1: 300,
            ph2: 375,
          },
          guard: 5,
          evade: 5,
          cres: 0,
        },
        hard: {
          lv: 110,
          exp: 8800,
          hp: 760000,
        },
        nm: {
          lv: 120,
          exp: 22000,
          hp: 1900000,
        },
        ulti: {
          lv: 140,
          exp: 44000,
          hp: 3800000,
        },
      },
    },
    {
      category: 'boss',
      name: 'B.B Goblin',
      loc: 'Rinom Plains',
      ele: 'fire',
      stats: {
        ez: {
          lv: 60,
          exp: 240,
          hp: undefined,
        },
        normal: {
          lv: 70,
          exp: 2400,
          hp: 24331,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 1,
          mres: 1,
          def: 140,
          mdef: 210,
          flee: 157,
          guard: 0,
          evade: 5,
          cres: 0,
        },
        hard: {
          lv: 80,
          exp: 4800,
          hp: undefined,
        },
        nm: {
          lv: 90,
          exp: 12000,
          hp: undefined,
        },
        ulti: {
          lv: 110,
          exp: 24000,
          hp: undefined,
        },
      },
    },
    {
      category: 'boss',
      name: 'Bexiz',
      loc: 'Cradle of Soldier: Deepest Part',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 93,
          exp: 761,
          hp: 64500,
        },
        normal: {
          lv: 103,
          exp: 7610,
          hp: 645000,
          npror: 35,
          ppror: 40,
          mpror: 50,
          pres: 4,
          mres: 4,
          def: 216,
          mdef: 247,
          flee: 123,
          guard: 15,
          evade: 1,
          cres: 0,
        },
        hard: {
          lv: 113,
          exp: 15220,
          hp: 1290000,
        },
        nm: {
          lv: 123,
          exp: 38050,
          hp: 3325000,
        },
        ulti: {
          lv: 143,
          exp: 76100,
          hp: 6450000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Black Knight of Delusion',
      loc: 'Abyss of No Return: Deepest Area',
      ele: 'dark',
      stats: {
        ez: {
          lv: 78,
          exp: 660,
          hp: 54000,
        },
        normal: {
          lv: 88,
          exp: 6600,
          hp: 540000,
          npror: 5,
          ppror: 30,
          mpror: 30,
          pres: {
            ph1: 23,
            ph2: 33,
          },
          mres: {
            ph1: 23,
            ph2: 33,
          },
          def: 176,
          mdef: 176,
          flee: 231,
          guard: 5,
          evade: 10,
          cres: 0,
        },
        hard: {
          lv: 98,
          exp: 13200,
          hp: 1080000,
        },
        nm: {
          lv: 108,
          exp: 33000,
          hp: 2700000,
        },
        ulti: {
          lv: 128,
          exp: 66000,
          hp: 5400000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Black Shadow',
      loc: 'Rokoko City Ruins',
      ele: {
        purple: 'dark',
        red: 'fire',
      },
      stats: {
        ez: {
          lv: 189,
          exp: 1250,
          hp: 278000,
        },
        normal: {
          lv: 199,
          exp: 12500,
          hp: 2780000,
          npror: 1,
          ppror: 10,
          mpror: 10,
          pres: {
            purple: 7,
            red: 27,
          },
          mres: {
            purple: 7,
            red: 27,
          },
          def: 398,
          mdef: 598,
          flee: 294,
          guard: undefined,
          evade: undefined,
          cres: 10,
        },
        hard: {
          lv: 209,
          exp: 25000,
          hp: 5560000,
        },
        nm: {
          lv: 219,
          exp: 62500,
          hp: 13900000,
        },
        ulti: {
          lv: 239,
          exp: 125000,
          hp: 27800000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Boss Colon',
      loc: 'Land Under Development',
      ele: 'earth',
      stats: {
        ez: {
          lv: 4,
          exp: 3,
          hp: 100,
        },
        normal: {
          lv: 10,
          exp: 30,
          hp: 1000,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 0,
          mres: 0,
          def: 7,
          mdef: 7,
          flee: 11,
          guard: 0,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 20,
          exp: 60,
          hp: 2000,
        },
        nm: {
          lv: 30,
          exp: 150,
          hp: 5000,
        },
        ulti: {
          lv: 50,
          exp: 300,
          hp: 10000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Boss Goblin',
      loc: 'Ribisco Cave: Deepest Part',
      ele: 'fire',
      stats: {
        ez: {
          lv: 30,
          exp: 56,
          hp: 2675,
        },
        normal: {
          lv: 40,
          exp: 560,
          hp: 26758,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 0,
          mres: 0,
          def: 30,
          mdef: 30,
          flee: 75,
          guard: 5,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 50,
          exp: 1120,
          hp: 53516,
        },
        nm: {
          lv: 60,
          exp: 2800,
          hp: 133790,
        },
        ulti: {
          lv: 80,
          exp: 5600,
          hp: 267580,
        },
      },
    },
    {
      category: 'boss',
      name: 'Boss Roga',
      loc: 'Saham Underground Cave - Deepest Part',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 52,
          exp: 300,
          hp: 25000,
        },
        normal: {
          lv: 62,
          exp: 3000,
          hp: 250000,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: {
            initial: 2,
            fts: 27,
          },
          mres: {
            initial: 2,
            fts: 27,
          },
          def: {
            initial: 62,
            fts: 186,
          },
          mdef: {
            initial: 62,
            fts: 186,
          },
          flee: {
            initial: 279,
            fts: 93,
          },
          guard: 10,
          evade: 5,
          cres: 0,
        },
        hard: {
          lv: 72,
          exp: 6000,
          hp: 500000,
        },
        nm: {
          lv: 82,
          exp: 15000,
          hp: 1250000,
        },
        ulti: {
          lv: 102,
          exp: 30000,
          hp: 2500000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Brutal Dragon Decel',
      loc: 'Nisel Mountain: The Top',
      ele: 'earth',
      stats: {
        ez: {
          lv: 30,
          exp: 56,
          hp: 5300,
        },
        normal: {
          lv: 40,
          exp: 560,
          hp: 53000,
          npror: 8,
          ppror: 20,
          mpror: 20,
          pres: 1,
          mres: 1,
          def: 20,
          mdef: 20,
          flee: 75,
          guard: 25,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 50,
          exp: 1120,
          hp: 106000,
        },
        nm: {
          lv: 60,
          exp: 2800,
          hp: 265000,
        },
        ulti: {
          lv: 80,
          exp: undefined,
          hp: undefined,
        },
      },
    },
    {
      category: 'boss',
      name: 'Cerberus',
      loc: 'Spring of Rebirth: Top',
      ele: {
        blue: 'water',
        red: 'fire',
        yellow: 'wind',
        white: 'neutral',
      },
      stats: {
        ez: {
          lv: 87,
          exp: 922,
          hp: 80000,
        },
        normal: {
          lv: 97,
          exp: 9220,
          hp: 800000,
          npror: 15,
          ppror: 20,
          mpror: 15,
          pres: {
            initial: 3,
            flinch: 50,
            stun: -5,
            lhp: 10,
          },
          mres: {
            initial: 3,
            tumble: 50,
            stun: -5,
            lhp: 10,
          },
          def: {
            initial: 146,
            flinch: 970,
            tumble: 49,
            stun: 97,
            lhp: 194,
          },
          mdef: {
            initial: 146,
            flinch: 49,
            tumble: 970,
            stun: 97,
            lhp: 194,
          },
          flee: {
            initial: 145,
            lhp: 174,
          },
          guard: {
            initial: 10,
            lhp: 15,
          },
          evade: {
            initial: 1,
            stun: 10,
            lhp: 5,
          },
          cres: 0,
        },
        hard: {
          lv: 107,
          exp: 18440,
          hp: 1600000,
        },
        nm: {
          lv: 117,
          exp: 46100,
          hp: 4000000,
        },
        ulti: {
          lv: 137,
          exp: 92200,
          hp: 8000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Crystal Titan',
      loc: 'Decaying Ruins',
      ele: 'dark',
      stats: {
        ez: {
          lv: 138,
          exp: 930,
          hp: 100000,
        },
        normal: {
          lv: 148,
          exp: 9300,
          hp: 1000000,
          npror: 20,
          ppror: 30,
          mpror: 27,
          pres: {
            initial: 25,
            ['break body']: 5,
            flinch: 100,
            stun: 100,
            lhp: 100,
          },
          mres: {
            initial: 25,
            ['break body']: 5,
            flinch: 100,
            stun: 100,
            lhp: 100,
          },
          def: {
            initial: 593,
            ['break body']: 401,
          },
          mdef: {
            initial: 678,
            ['break body']: 359,
          },
          flee: 111,
          guard: 5,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 158,
          exp: 18600,
          hp: 2000000,
        },
        nm: {
          lv: 168,
          exp: 46500,
          hp: 5000000,
        },
        ulti: {
          lv: 188,
          exp: 93000,
          hp: 10000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Demonic Quasar',
      loc: 'Morga Wasteland: Deepest Area',
      ele: 'dark',
      stats: {
        ez: {
          lv: 175,
          exp: 4050,
          hp: 800000,
        },
        normal: {
          lv: 185,
          exp: 40500,
          hp: 8000000,
          npror: 5,
          ppror: 5,
          mpror: 5,
          pres: 7,
          mres: 7,
          def: 925,
          mdef: 925,
          flee: 259,
          guard: undefined,
          evade: undefined,
          cres: 25,
        },
        hard: {
          lv: 195,
          exp: 81000,
          hp: 16000000,
        },
        nm: {
          lv: 205,
          exp: 202500,
          hp: 40000000,
        },
        ulti: {
          lv: 225,
          exp: 405000,
          hp: 80000000,
        },
      },
    },
    {
      category: 'boss',
      name: "Demon's Gate",
      loc: 'Saham Crater',
      ele: 'dark',
      stats: {
        ez: {
          lv: 50,
          exp: 144,
          hp: 180000,
        },
        normal: {
          lv: 60,
          exp: 1440,
          hp: 18000,
          npror: 150,
          ppror: 1,
          mpror: 1,
          pres: {
            initial: 2,
            flinch: 20,
          },
          mres: {
            initial: 2,
            flinch: 20,
          },
          def: 180,
          mdef: 180,
          flee: 0,
          guard: {
            initial: 0,
            flinch: 100,
          },
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 70,
          exp: 2880,
          hp: 360000,
        },
        nm: {
          lv: 80,
          exp: 7200,
          hp: 900000,
        },
        ulti: {
          lv: 100,
          exp: 14400,
          hp: 1800000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Eerie Crystal',
      loc: "Isthmus Of Kaus: Dragon's Den",
      ele: 'dark',
      stats: {
        ez: {
          lv: 14,
          exp: 22,
          hp: 630,
        },
        normal: {
          lv: 24,
          exp: 225,
          hp: 6300,
          npror: 30,
          ppror: 5,
          mpror: 5,
          pres: 0,
          mres: 0,
          def: 0,
          mdef: 0,
          flee: 0,
          guard: 5,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 34,
          exp: 450,
          hp: 12600,
        },
        nm: {
          lv: 44,
          exp: 1125,
          hp: 31500,
        },
        ulti: {
          lv: 64,
          exp: 2250,
          hp: 63000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Eroded Pilz',
      loc: 'Morthell Swell: Deep Area',
      ele: {
        purple: 'fire',
        green: 'neutral',
      },
      stats: {
        ez: {
          lv: 162,
          exp: 1870,
          hp: 236000,
        },
        normal: {
          lv: 172,
          exp: 18700,
          hp: 2360000,
          npror: 5,
          ppror: 20,
          mpror: 5,
          pres: {
            initial: 26,
            ['break right']: 6,
            ['break head']: 20,
            ['break right+head']: 0,
          },
          mres: {
            initial: 26,
            ['break right']: 6,
            ['break head']: 20,
            ['break right+head']: 0,
          },
          def: {
            initial: 602,
            green: 1204,
            ['break right']: 421,
          },
          mdef: {
            initial: 499,
            green: 998,
            ['break right']: 349,
          },
          flee: 258,
          guard: undefined,
          evade: undefined,
          cres: {
            purple: 23,
            green: 40,
          },
        },
        hard: {
          lv: 182,
          exp: 37400,
          hp: 4720000,
        },
        nm: {
          lv: 192,
          exp: 93500,
          hp: 11800000,
        },
        ulti: {
          lv: 212,
          exp: 187000,
          hp: 23600000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Evil Crystal Beast',
      loc: 'Lunagent Mountain: Deepest Area',
      ele: 'dark',
      stats: {
        ez: {
          lv: 81,
          exp: 630,
          hp: 53000,
        },
        normal: {
          lv: 91,
          exp: 6300,
          hp: 530000,
          npror: 5,
          ppror: 30,
          mpror: 30,
          pres: 3,
          mres: 3,
          def: {
            ph1: 274,
            ph2: 165,
          },
          mdef: {
            ph1: 320,
            ph2: 183,
          },
          flee: {
            ph1: 136,
            ph2: 163,
          },
          guard: {
            ftsd: 110,
            ph1: 30,
            ph2: 10,
          },
          evade: {
            ph1: {
              initial: 30,
              ftsd: 110,
            },
            ph2: {
              initial: 5,
              ftsd: 100,
            },
          },
          cres: 0,
        },
        hard: {
          lv: 101,
          exp: 12600,
          hp: 1060000,
        },
        nm: {
          lv: 111,
          exp: 31500,
          hp: 2650000,
        },
        ulti: {
          lv: 131,
          exp: 63000,
          hp: 5300000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Excavated Golem',
      loc: 'Underground Ruins: Deepest Part',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 6,
          exp: 9,
          hp: 315,
        },
        normal: {
          lv: 16,
          exp: 90,
          hp: 3150,
          npror: 10,
          ppror: 15,
          mpror: 15,
          pres: 0,
          mres: 0,
          def: 12,
          mdef: 12,
          flee: 12,
          guard: 5,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 26,
          exp: 180,
          hp: 6300,
        },
        nm: {
          lv: 36,
          exp: 450,
          hp: 15750,
        },
        ulti: {
          lv: 56,
          exp: 900,
          hp: 31500,
        },
      },
    },
    {
      category: 'boss',
      name: 'Ferzen the Rock Dragon',
      loc: 'Guardian Forest: Giant Tree',
      ele: 'earth',
      stats: {
        ez: {
          lv: 201,
          exp: 1515,
          hp: 317100,
        },
        normal: {
          lv: 211,
          exp: 15150,
          hp: 3171000,
          npror: 10,
          ppror: 10,
          mpror: 20,
          pres: 8,
          mres: 8,
          def: {
            initial: 1055,
            ['break head']: 'current - 52',
            ['break tail']: 'current - 52',
            ['break body']: 'current - 104',
          },
          mdef: {
            initial: 740,
            ['break head']: 'current - 28',
            ['break tail']: 'current - 28',
            ['break body']: 'current - 54',
          },
          flee: 314,
          guard: undefined,
          evade: undefined,
          cres: 20,
        },
        hard: {
          lv: 221,
          exp: 30300,
          hp: 6342000,
        },
        nm: {
          lv: 231,
          exp: 75750,
          hp: 15855000,
        },
        ulti: {
          lv: 251,
          exp: 151500,
          hp: 31710000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Finstern the Dark Dragon',
      loc: 'Dark Dragon Shrine: Near the Top',
      ele: 'dark',
      stats: {
        ez: {
          lv: 156,
          exp: 1400,
          hp: 240000,
        },
        normal: {
          lv: 166,
          exp: 14000,
          hp: 2400000,
          npror: 100,
          ppror: 1,
          mpror: 10,
          pres: {
            ph1: 6,
            ph2: 16,
          },
          mres: {
            ph1: 6,
            ph2: 16,
          },
          def: 249,
          mdef: 249,
          flee: 25,
          guard: 1,
          evade: 1,
          cres: {
            ph1: 0,
            ph2: {
              initial: 125,
              fts: 25,
            },
          },
        },
        hard: {
          lv: 176,
          exp: 6342000,
          hp: 30300,
        },
        nm: {
          lv: 186,
          exp: 70000,
          hp: 12000000,
        },
        ulti: {
          lv: 206,
          exp: 140000,
          hp: 24000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Flare Volg',
      loc: 'Fiery Volcano: Boss Map',
      ele: 'fire',
      stats: {
        ez: {
          lv: 40,
          exp: 150,
          hp: 12000,
        },
        normal: {
          lv: 50,
          exp: 1500,
          hp: 120000,
          npror: 6,
          ppror: 25,
          mpror: 25,
          pres: 2,
          mres: 2,
          def: {
            ph1: 100,
            ph2: 62,
          },
          mdef: {
            ph1: 100,
            ph2: 62,
          },
          flee: 56,
          guard: 0,
          evade: {
            ph1: 25,
            ph2: 10,
          },
          cres: 0,
        },
        hard: {
          lv: 60,
          exp: 3000,
          hp: 240000,
        },
        nm: {
          lv: 70,
          exp: 7500,
          hp: 600000,
        },
        ulti: {
          lv: 90,
          exp: 15000,
          hp: 1200000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Forest Wolf',
      loc: 'Marbaro Forest: Deepest Part',
      ele: 'wind',
      stats: {
        ez: {
          lv: 20,
          exp: 30,
          hp: 1603,
        },
        normal: {
          lv: 20,
          exp: 300,
          hp: 16038,
          npror: 8,
          ppror: 20,
          mpror: 20,
          pres: 0,
          mres: 0,
          def: 30,
          mdef: 30,
          flee: 45,
          guard: 10,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 40,
          exp: 600,
          hp: 32076,
        },
        nm: {
          lv: 50,
          exp: 1500,
          hp: 80190,
        },
        ulti: {
          lv: 70,
          exp: 3000,
          hp: 160380,
        },
      },
    },
    {
      category: 'boss',
      name: 'Forestia',
      loc: 'Land Of Chaos',
      ele: 'wind',
      stats: {
        ez: {
          lv: 39,
          exp: 148,
          hp: 13500,
        },
        normal: {
          lv: 49,
          exp: 1480,
          hp: 135000,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 1,
          mres: 1,
          def: 24,
          mdef: 24,
          flee: 292,
          guard: 0,
          evade: 10,
          cres: 0,
        },
        hard: {
          lv: 59,
          exp: 2960,
          hp: 270000,
        },
        nm: {
          lv: 69,
          exp: 7400,
          hp: 675000,
        },
        ulti: {
          lv: 89,
          exp: 14800,
          hp: 1350000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Ganglef',
      loc: 'Scaro Town: Deepest Part',
      ele: 'earth',
      stats: {
        ez: {
          lv: 48,
          exp: 115,
          hp: 10780,
        },
        normal: {
          lv: 58,
          exp: 1150,
          hp: 107800,
          npror: 6,
          ppror: 25,
          mpror: 25,
          pres: 1,
          mres: 5,
          def: 232,
          mdef: 58,
          flee: 43,
          guard: 20,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 68,
          exp: 2300,
          hp: 215600,
        },
        nm: {
          lv: 78,
          exp: 2960,
          hp: 270000,
        },
        ulti: {
          lv: 98,
          exp: 11500,
          hp: 1078000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Gemma',
      loc: 'Fugitive Lake Swamp: Depths',
      ele: {
        initial: 'fire',
        yellow: 'earth',
        green: 'light',
      },
      stats: {
        ez: {
          lv: 198,
          exp: 1408,
          hp: 288400,
        },
        normal: {
          lv: 208,
          exp: 14080,
          hp: 2884000,
          npror: 10,
          ppror: 5,
          mpror: 5,
          pres: 16,
          mres: 20,
          def: 730,
          mdef: 700,
          flee: 465,
          guard: undefined,
          evade: undefined,
          cres: 20,
        },
        hard: {
          lv: 218,
          exp: 28160,
          hp: 5768000,
        },
        nm: {
          lv: 228,
          exp: 70400,
          hp: 14420000,
        },
        ulti: {
          lv: 248,
          exp: 140800,
          hp: 28840000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Gespenst',
      loc: 'Underground Channel',
      ele: 'dark',
      stats: {
        ez: {
          lv: 10,
          exp: 24,
          hp: 854,
        },
        normal: {
          lv: 20,
          exp: 240,
          hp: 8544,
          npror: 20,
          ppror: 30,
          mpror: 15,
          pres: 0,
          mres: 0,
          def: 26,
          mdef: 50,
          flee: 30,
          guard: 0,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 30,
          exp: 480,
          hp: 17088,
        },
        nm: {
          lv: 40,
          exp: 1200,
          hp: 42720,
        },
        ulti: {
          lv: 60,
          exp: 2400,
          hp: 85440,
        },
      },
    },
    {
      category: 'boss',
      name: 'Goovua',
      loc: 'Akaku Desert: Hill',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 72,
          exp: 500,
          hp: 40000,
        },
        normal: {
          lv: 82,
          exp: 5000,
          hp: 400000,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 3,
          mres: 3,
          def: {
            ph1: 41,
            ph2: 57,
            ph3: 82,
            lhp: 0,
          },
          mdef: {
            ph1: 41,
            ph2: 57,
            ph3: 82,
            lhp: 0,
          },
          flee: {
            ph1: 246,
            ph2: 273,
            ph3: 308,
            lhp: 0,
          },
          guard: {
            initial: 5,
            lhp: 0,
          },
          evade: {
            ph1: 5,
            ph2: 15,
            ph3: 25,
            lhp: 0,
          },
          cres: 0,
        },
        hard: {
          lv: 92,
          exp: 10000,
          hp: 800000,
        },
        nm: {
          lv: 102,
          exp: 25000,
          hp: 2000000,
        },
        ulti: {
          lv: 122,
          exp: 50000,
          hp: 4000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Grass Dragon Yelb',
      loc: 'Albatif Village',
      ele: 'earth',
      stats: {
        ez: {
          lv: 63,
          exp: 504,
          hp: 43919,
        },
        normal: {
          lv: 73,
          exp: 5040,
          hp: 439190,
          npror: 3,
          ppror: 50,
          mpror: 50,
          pres: {
            initial: 2,
            shell: 22,
          },
          mres: {
            initial: 2,
            shell: 22,
          },
          def: {
            initial: 146,
            shell: 1022,
          },
          mdef: {
            initial: 219,
            shell: 657,
          },
          flee: 87,
          guard: {
            initial: 30,
            shell: 40,
          },
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 83,
          exp: 10080,
          hp: 878380,
        },
        nm: {
          lv: 93,
          exp: 25200,
          hp: 2195950,
        },
        ulti: {
          lv: 113,
          exp: 50400,
          hp: 4391900,
        },
      },
    },
    {
      category: 'boss',
      name: 'Gravicep',
      loc: 'Recetacula Sector: Depot Rooftop',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 174,
          exp: 1919,
          hp: 515000,
        },
        normal: {
          lv: 184,
          exp: 19190,
          hp: 5150000,
          npror: 1,
          ppror: 100,
          mpror: 100,
          pres: {
            ['aggro <= 7m']: 21,
            ['aggro > 7m']: 7,
          },
          mres: {
            ['aggro <= 7m']: 7,
            ['aggro > 7m']: 21,
          },
          def: {
            ['aggro <= 7m']: 552,
            ['aggro > 7m']: 185,
          },
          mdef: {
            ['aggro <= 7m']: 185,
            ['aggro > 7m']: 552,
          },
          flee: {
            ['aggro <= 7m']: 275,
            ['aggro > 7m']: 547,
          },
          guard: undefined,
          evade: undefined,
          cres: 0,
        },
        hard: {
          lv: 194,
          exp: 38380,
          hp: 10300000,
        },
        nm: {
          lv: 204,
          exp: 95950,
          hp: 25750000,
        },
        ulti: {
          lv: 224,
          exp: 191900,
          hp: 51500000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Guignol',
      loc: 'Brahe Laboratory: 4th Building',
      ele: 'wind',
      stats: {
        ez: {
          lv: 123,
          exp: 620,
          hp: 49000,
        },
        normal: {
          lv: 133,
          exp: 6200,
          hp: 490000,
          npror: 50,
          ppror: 6,
          mpror: 6,
          pres: {
            blue: 80,
            yellow: 55,
            red: 30,
          },
          mres: {
            blue: 80,
            yellow: 55,
            red: 30,
          },
          def: 399,
          mdef: 0,
          flee: 299,
          guard: 0,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 143,
          exp: 12400,
          hp: 980000,
        },
        nm: {
          lv: 153,
          exp: 31000,
          hp: 2450000,
        },
        ulti: {
          lv: 173,
          exp: 62000,
          hp: 4900000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Gwaimol',
      loc: 'Cuervo Jail: Roof',
      ele: 'earth',
      stats: {
        ez: {
          lv: 126,
          exp: 810,
          hp: 85000,
        },
        normal: {
          lv: 136,
          exp: 8100,
          hp: 850000,
          npror: 3,
          ppror: 1,
          mpror: 2,
          pres: 5,
          mres: 5,
          def: 215,
          mdef: 216,
          flee: 204,
          guard: 15,
          evade: 5,
          cres: 25,
        },
        hard: {
          lv: 146,
          exp: 16200,
          hp: 1700000,
        },
        nm: {
          lv: 156,
          exp: 40500,
          hp: 4250000,
        },
        ulti: {
          lv: 176,
          exp: 81000,
          hp: 8500000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Hexter',
      loc: "Witch's Woods Depths",
      ele: 'wind',
      stats: {
        ez: {
          lv: 192,
          exp: 1342,
          hp: 272000,
        },
        normal: {
          lv: 202,
          exp: 13420,
          hp: 2720000,
          npror: 5,
          ppror: 5,
          mpror: 25,
          pres: 8,
          mres: 8,
          def: 607,
          mdef: 606,
          flee: 285,
          guard: undefined,
          evade: undefined,
          cres: {
            initial: 25,
            ['every 60sec']: 100,
          },
        },
        hard: {
          lv: 212,
          exp: 26840,
          hp: 5440000,
        },
        nm: {
          lv: 222,
          exp: 67100,
          hp: 13600000,
        },
        ulti: {
          lv: 242,
          exp: 134200,
          hp: 27200000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Iconos',
      loc: 'Artillery Defense Line',
      ele: 'earth',
      stats: {
        ez: {
          lv: 98,
          exp: 420,
          hp: 40400,
        },
        normal: {
          lv: 108,
          exp: 4200,
          hp: 404000,
          npror: 0,
          ppror: 0,
          mpror: 0,
          pres: {
            ph1: 10,
            ph2: 15,
            ph3: 20,
            ph4: 25,
          },
          mres: {
            ph1: 10,
            ph2: 15,
            ph3: 20,
            ph4: 25,
          },
          def: {
            ph1: 162,
            ph2: 216,
            ph3: 270,
            ph4: 324,
          },
          mdef: {
            ph1: 140,
            ph2: 194,
            ph3: 248,
            ph4: 302,
          },
          flee: 162,
          guard: {
            tumble: 100,
            ph1: 5,
            ph2: 10,
            ph3: 15,
            ph4: 20,
          },
          evade: {
            PH1: 0,
            PH2: 0,
            PH3: 0,
            PH4: 2,
          },
          cres: {
            initial: 25,
            ['every 60sec']: 100,
          },
        },
        hard: {
          lv: 118,
          exp: 8400,
          hp: 808000,
        },
        nm: {
          lv: 128,
          exp: 21000,
          hp: 2020000,
        },
        ulti: {
          lv: 148,
          exp: 42000,
          hp: 4040000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Ifrid',
      loc: 'Blazing Graben: Deepest Part',
      ele: 'fire',
      stats: {
        ez: {
          lv: 102,
          exp: 600,
          hp: 55550,
        },
        normal: {
          lv: 112,
          exp: 6000,
          hp: 555500,
          npror: 30,
          ppror: 30,
          mpror: 15,
          pres: 4,
          mres: 4,
          def: 179,
          mdef: 158,
          flee: 185,
          guard: 5,
          evade: 5,
          cres: 0,
        },
        hard: {
          lv: 122,
          exp: 12000,
          hp: 1111000,
        },
        nm: {
          lv: 132,
          exp: 30000,
          hp: 2777500,
        },
        ulti: {
          lv: 152,
          exp: 60000,
          hp: 5555000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Imitacia',
      loc: 'Dark Castle: Grand Hall',
      ele: 'fire',
      stats: {
        ez: {
          lv: 99,
          exp: 815,
          hp: 72000,
        },
        normal: {
          lv: 109,
          exp: 8150,
          hp: 720000,
          npror: 30,
          ppror: 35,
          mpror: 40,
          pres: {
            frozen: 10,
            ph1: 35,
            ph2: 4,
          },
          mres: {
            frozen: 10,
            ph1: 35,
            ph2: 4,
          },
          def: {
            frozen: 33,
            ph1: 164,
            ph2: 55,
          },
          mdef: {
            frozen: 33,
            ph1: 218,
            ph2: 109,
          },
          flee: {
            frozen: 163,
            ph1: 302,
            ph2: 489,
          },
          guard: {
            frozen: 0,
            ph1: 5,
            ph2: 0,
          },
          evade: {
            frozen: 0,
            ph1: 5,
            ph2: 10,
          },
          cres: 0,
        },
        hard: {
          lv: 119,
          exp: 16300,
          hp: 1440000,
        },
        nm: {
          lv: 129,
          exp: 40750,
          hp: 3600000,
        },
        ulti: {
          lv: 149,
          exp: 81500,
          hp: 7200000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Imitator',
      loc: 'Plastida: Deepest Part',
      ele: 'fire',
      stats: {
        ez: {
          lv: 96,
          exp: 870,
          hp: 78000,
        },
        normal: {
          lv: 106,
          exp: 8700,
          hp: 780000,
          npror: 30,
          ppror: 35,
          mpror: 35,
          pres: 20,
          mres: 20,
          def: 371,
          mdef: 392,
          flee: 238,
          guard: 20,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 116,
          exp: 17400,
          hp: 1560000,
        },
        nm: {
          lv: 126,
          exp: 43500,
          hp: 3900000,
        },
        ulti: {
          lv: 146,
          exp: 87000,
          hp: 7800000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Inzanio the Dark Knight',
      loc: 'Fort Solfini: Roof',
      ele: 'water',
      stats: {
        ez: {
          lv: 84,
          exp: 550,
          hp: 48900,
        },
        normal: {
          lv: 94,
          exp: 5500,
          hp: 489000,
          npror: 4,
          ppror: 35,
          mpror: 35,
          pres: 3,
          mres: 3,
          def: {
            ph1: 212,
            ph2: 263,
          },
          mdef: {
            ph1: 188,
            ph2: 235,
          },
          flee: 176,
          guard: {
            initial: 15,
            flinch: 100,
          },
          evade: 500,
          cres: 0,
        },
        hard: {
          lv: 104,
          exp: 11000,
          hp: 978000,
        },
        nm: {
          lv: 114,
          exp: 27500,
          hp: 2445000,
        },
        ulti: {
          lv: 134,
          exp: 55000,
          hp: 4890000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Irestida',
      loc: 'Nov Diela Central',
      ele: {
        blue: 'neutral',
        green: 'wind',
      },
      stats: {
        ez: {
          lv: 195,
          exp: 1446,
          hp: 294000,
        },
        normal: {
          lv: 205,
          exp: 14460,
          hp: 2940000,
          npror: 1,
          ppror: 1,
          mpror: 50,
          pres: 8,
          mres: 8,
          def: 922,
          mdef: 311,
          flee: 265,
          guard: undefined,
          evade: undefined,
          cres: {
            initial: 100,
            freeze: 0,
          },
        },
        hard: {
          lv: 215,
          exp: 28920,
          hp: 5880000,
        },
        nm: {
          lv: 225,
          exp: 72300,
          hp: 14700000,
        },
        ulti: {
          lv: 245,
          exp: 144600,
          hp: 29400000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Jade Raptor',
      loc: 'Gravel Terrace',
      ele: 'wind',
      stats: {
        ez: {
          lv: 69,
          exp: 840,
          hp: 62000,
        },
        normal: {
          lv: 79,
          exp: 8400,
          hp: 620000,
          npror: 4,
          ppror: 4,
          mpror: 40,
          pres: 3,
          mres: 3,
          def: 158,
          mdef: 198,
          flee: 177,
          guard: {
            initial: 45,
            fts: 35,
          },
          evade: {
            initial: 0,
            fts: -10,
          },
          cres: 0,
        },
        hard: {
          lv: 89,
          exp: 16800,
          hp: 1240000,
        },
        nm: {
          lv: 99,
          exp: 42000,
          hp: 3100000,
        },
        ulti: {
          lv: 119,
          exp: 84000,
          hp: 6200000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Junior Dragon Zyvio',
      loc: 'Storage Yard: Arena',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 204,
          exp: 1620,
          hp: 355000,
        },
        normal: {
          lv: 214,
          exp: 16200,
          hp: 3550000,
          npror: 5,
          ppror: 5,
          mpror: 10,
          pres: 8,
          mres: 12,
          def: 642,
          mdef: 526,
          flee: undefined,
          guard: undefined,
          evade: undefined,
          cres: undefined,
        },
        hard: {
          lv: 224,
          exp: 32400,
          hp: 7100000,
        },
        nm: {
          lv: 234,
          exp: 81000,
          hp: 17750000,
        },
        ulti: {
          lv: 254,
          exp: 162000,
          hp: 35500000,
        },
      },
    },
    {
      category: 'boss',
      name: 'King Piton',
      loc: 'Elf Mountains: Shrine',
      ele: 'water',
      stats: {
        ez: {
          lv: 153,
          exp: 1200,
          hp: 160000,
        },
        normal: {
          lv: 163,
          exp: 12000,
          hp: 1600000,
          npror: 30,
          ppror: 30,
          mpror: 30,
          pres: {
            initial: 15,
            ['break 1part']: 10,
            ['break 2parts']: 5,
            ['break 3parts']: 0,
          },
          mres: {
            initial: 15,
            ['break 1part']: 10,
            ['break 2parts']: 5,
            ['break 3parts']: 0,
          },
          def: {
            initial: 789,
            ['break 1part']: 690,
            ['break 2parts']: 589,
            ['break 3parts']: 489,
          },
          mdef: {
            initial: 244,
            ['break 1part']: 202,
            ['break 2parts']: 171,
            ['break 3parts']: 142,
          },
          flee: 122,
          guard: 20,
          evade: 5,
          cres: 7,
        },
        hard: {
          lv: 173,
          exp: 24000,
          hp: 3200000,
        },
        nm: {
          lv: 183,
          exp: 60000,
          hp: 8000000,
        },
        ulti: {
          lv: 203,
          exp: 120000,
          hp: 16000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Kuzto',
      loc: 'Labilans Sector: Square',
      ele: 'earth',
      stats: {
        ez: {
          lv: 168,
          exp: 1820,
          hp: 350000,
        },
        normal: {
          lv: 178,
          exp: 18200,
          hp: 3500000,
          npror: 20,
          ppror: 5,
          mpror: 5,
          pres: 7,
          mres: 7,
          def: 537,
          mdef: 537,
          flee: 267,
          guard: undefined,
          evade: undefined,
          cres: 25,
        },
        hard: {
          lv: 188,
          exp: 36400,
          hp: 7000000,
        },
        nm: {
          lv: 198,
          exp: 91000,
          hp: 17500000,
        },
        ulti: {
          lv: 218,
          exp: 182000,
          hp: 35000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Lalvada',
      loc: "Monster's Forest: Deep Part",
      ele: 'light',
      stats: {
        ez: {
          lv: 117,
          exp: 600,
          hp: 60000,
        },
        normal: {
          lv: 127,
          exp: 6000,
          hp: 600000,
          npror: 10,
          ppror: 34,
          mpror: 44,
          pres: 15,
          mres: 15,
          def: {
            green: 449,
            yellow: 685,
            ph2: 685,
          },
          mdef: {
            green: 524,
            yellow: 552,
            ph2: 552,
          },
          flee: 228,
          guard: 5,
          evade: {
            initial: 3,
            yellow: {
              initial: 3,
              red: 100,
            },
          },
          cres: 0,
        },
        hard: {
          lv: 137,
          exp: 12000,
          hp: 1200000,
        },
        nm: {
          lv: 147,
          exp: 30000,
          hp: 3000000,
        },
        ulti: {
          lv: 167,
          exp: 60000,
          hp: 6000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Mardula',
      loc: 'Hall of Blessings Gods',
      ele: {
        ph1: {
          initial: 'light',
          ['break spear']: 'wind',
        },
        ph2: 'neutral',
      },
      stats: {
        ez: {
          lv: 147,
          exp: 810,
          hp: 142000,
        },
        normal: {
          lv: 157,
          exp: 8100,
          hp: 1420000,
          npror: 10,
          ppror: 5,
          mpror: 5,
          pres: 6,
          mres: 6,
          def: 157,
          mdef: 394,
          flee: 470,
          guard: 2,
          evade: 10,
          cres: 10,
        },
        hard: {
          lv: 167,
          exp: 16200,
          hp: 2840000,
        },
        nm: {
          lv: 177,
          exp: 40500,
          hp: 7100000,
        },
        ulti: {
          lv: 197,
          exp: 81000,
          hp: 14200000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Masked Warrior',
      loc: 'Land Under Cultivation: Hill',
      ele: 'fire',
      stats: {
        ez: {
          lv: 57,
          exp: 430,
          hp: 27600,
        },
        normal: {
          lv: 67,
          exp: 4300,
          hp: 276000,
          npror: 6,
          ppror: 25,
          mpror: 25,
          pres: 2,
          mres: 2,
          def: 134,
          mdef: 134,
          flee: 200,
          guard: 5,
          evade: 5,
          cres: 0,
        },
        hard: {
          lv: 77,
          exp: 8600,
          hp: 522000,
        },
        nm: {
          lv: 87,
          exp: 21500,
          hp: 1380000,
        },
        ulti: {
          lv: 107,
          exp: 43000,
          hp: 2760000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Maton Sword',
      loc: 'Buried Tower: Entrance',
      ele: 'wind',
      stats: {
        ez: {
          lv: 133,
          exp: 1100,
          hp: 200000,
        },
        normal: {
          lv: 143,
          exp: 11000,
          hp: 2000000,
          npror: 5,
          ppror: 6,
          mpror: 6,
          pres: 15,
          mres: 15,
          def: {
            ph1: 400,
            ph2: 200,
            ph3: 800,
            ph4: {
              initial: 4000,
              ['paralyze/stop']: 400,
            },
          },
          mdef: {
            ph1: 500,
            ph2: 1000,
            ph3: 250,
            ph4: {
              initial: 5000,
              ['paralyze/stop']: 500,
            },
          },
          flee: 428,
          guard: 0,
          evade: 0,
          cres: 0,
        },
        hard: {
          lv: 153,
          exp: 22000,
          hp: 4000000,
        },
        nm: {
          lv: 163,
          exp: 55000,
          hp: 10000000,
        },
        ulti: {
          lv: 183,
          exp: 110000,
          hp: 20000000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Mauez',
      loc: 'New Moon Palace: Innermost',
      ele: 'water',
      stats: {
        ez: {
          lv: 45,
          exp: 129,
          hp: 8600,
        },
        normal: {
          lv: 55,
          exp: 1290,
          hp: 86000,
          npror: 15,
          ppror: 10,
          mpror: 10,
          pres: 7,
          mres: 7,
          def: {
            ph1: 165,
            ph2: 28,
          },
          mdef: {
            ph1: 165,
            ph2: 28,
          },
          flee: {
            ph1: 41,
            ph2: 246,
          },
          guard: {
            ph1: 35,
            ph2: 10,
          },
          evade: {
            ph1: 5,
            ph2: 30,
          },
          cres: 0,
        },
        hard: {
          lv: 65,
          exp: 2580,
          hp: 172000,
        },
        nm: {
          lv: 75,
          exp: 6450,
          hp: 430000,
        },
        ulti: {
          lv: 95,
          exp: 12900,
          hp: 860000,
        },
      },
    },
    {
      category: 'boss',
      name: 'Memecoleolus',
      loc: 'Dark Castle: Area 2',
      ele: 'neutral',
      stats: {
        ez: {
          lv: 90,
          exp: 1440,
          hp: 129000,
        },
        normal: {
          lv: 100,
          exp: 14400,
          hp: 1290000,
          npror: 40,
          ppror: 20,
          mpror: 40,
          pres: 4,
          mres: 4,
          def: 220,
          mdef: 242,
          flee: 248,
          guard: 10,
          evade: 2,
          cres: 0,
        },
        hard: {
          lv: 110,
          exp: 28800,
          hp: 2580000,
        },
        nm: {
          lv: 120,
          exp: 72000,
          hp: 6450000,
        },
        ulti: {
          lv: 140,
          exp: 144000,
          hp: 12900000,
        },
      },
    },
  ],
  miniboss: [
    {
      category: 'miniboss',
      name: 'Dark Mushroom',
      lv: 30,
      loc: 'Isthmus of Kaus',
      exp: 440,
      hp: 17500,
      ele: 'dark',
      def: 30,
      pres: 1,
      mdef: 30,
      mres: 1,
      npror: 5,
      ppror: 25,
      mpror: 50,
      flee: 34,
      cres: 0,
    },
  ],
};
allList.all = [...allList.boss, ...allList.miniboss];
