on:
  push:
    branches:
      - main
name: Deploy Production Web on push in branch main

jobs:
  deploy-production:
    name: 'Deploy Production'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Use Node defined in .nvmrc (18.17.1)
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
      - run: node --version

      - uses: actions/checkout@v4
      - name: Install Packages
        run: npm ci

      - name: See folder structure
        run: |
          pwd
          ls

      - name: Build & Deploy project
        run: |
          npm run build
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          npm run deploy
